### ISSUE TITLE
Failed to convert to ATV 11

### ISSUE THREAD

**Issue by eagledipesh** [t1m0xa/ATVify#2]
Failing to convert AOSP 11 to ATV, AOSP version of ROM boots fine on S912 boxes hence I thought I could simply convert this to ATV and try if that works, I tried all the instructions you have provided, unfortunately it fails? 

Below is the link to download the ROM, could you please check and help?

https://disk.yandex.com/d/LF8hmBSrz7adrw
https://disk.yandex.com/d/SDJxTbAbv0svQA

**Comment by t1m0xa** [comment]
Hello! What exactly doesn't work, converting or the ROM?

**Comment by eagledipesh** [comment]
ROM installs fine, but when I try to convert it to ATV it fails.

**Comment by t1m0xa** [comment]
Ok. You can try remove spaces from folder name.

**Comment by eagledipesh** [comment]
On i have moved the folder to the root of the drive. see the logs below.

It fails when trying to unpack super.img.raw

<EDIT> did some reasearch and this could be possible fix, could you confimr?
https://forum.xda-developers.com/t/extracing-super-img-super2-img-issue-and-mounting-vendor-img.4279879/

> Firmware unpacking...
> [Msg]Image package version 0x2
> [Msg]Unpack item [USB         ,              DDR] to (level1\DDR.USB) size:49152 bytes
> [Msg]Unpack item [USB         ,            UBOOT] to (level1\UBOOT.USB) size:786432 bytes
> [Msg]Unpack item [PARTITION   ,         _aml_dtb] to (level1\_aml_dtb.PARTITION) size:59203 bytes
> [Msg]Unpack item [UBOOT       ,     aml_sdc_burn] to (level1\aml_sdc_burn.UBOOT) size:836096 bytes
> [Msg]Unpack item [ini         ,     aml_sdc_burn] to (level1\aml_sdc_burn.ini) size:394 bytes
> [Msg]Unpack item [PARTITION   ,             boot] to (level1\boot.PARTITION) size:9885696 bytes
> [Msg]Unpack item [PARTITION   ,       bootloader] to (level1\bootloader.PARTITION) size:868352 bytes
> [Msg]Unpack item [PARTITION   ,             dtbo] to (level1\dtbo.PARTITION) size:438 bytes
> [Msg]Unpack item [PARTITION   ,             logo] to (level1\logo.PARTITION) size:5048640 bytes
> [Msg]Backup item [dtb         ,           meson1] backItemId[2][PARTITION, _aml_dtb]
> [Msg]Unpack item [PARTITION   ,              odm] to (level1\odm.PARTITION) size:540748 bytes
> [Msg]Unpack item [conf        ,         platform] to (level1\platform.conf) size:202 bytes
> [Msg]Unpack item [PARTITION   ,          product] to (level1\product.PARTITION) size:3469388 bytes
> [Msg]Unpack item [PARTITION   ,         recovery] to (level1\recovery.PARTITION) size:16756736 bytes
> [Msg]Unpack item [PARTITION   ,           system] to (level1\system.PARTITION) size:1344848260 bytes
> [Msg]Unpack item [PARTITION   ,           vbmeta] to (level1\vbmeta.PARTITION) size:4096 bytes
> [Msg]Unpack item [PARTITION   ,           vendor] to (level1\vendor.PARTITION) size:106212184 bytes
> [Msg]Write config file "level1\image.cfg" OK!
> Image unpack OK!
> Convert super.img to super.img.raw
> Cannot open input file level1\super.PARTITION
> Unpack super.img.raw
> lpunpack E 07-30 14:06:42   665 15216 reader.cpp:125] [liblp]bool android::fs_mgr::ReadPrimaryGeometry(int, LpMetadataGeometry *) read 4096 bytes failed: No error
> lpunpack E 07-30 14:06:42   665 15216 reader.cpp:138] [liblp]bool android::fs_mgr::ReadBackupGeometry(int, LpMetadataGeometry *) backup read 4096 bytes failed: No error
> Image does not appear to be in super-partition format.
> Unpack odm_a.img
> imgextractor: Vortex Edition
> Traceback (most recent call last):
>   File "imgextractor.py", line 374, in <module>
>   File "imgextractor.py", line 360, in main
>   File "imgextractor.py", line 345, in __getTypeTarget
> FileNotFoundError: [Errno 2] No such file or directory: 'level2\\odm_a.img'
> [52] Failed to execute script imgextractor
> Unpack product_a.img
> imgextractor: Vortex Edition
> Traceback (most recent call last):
>   File "imgextractor.py", line 374, in <module>
>   File "imgextractor.py", line 360, in main
>   File "imgextractor.py", line 345, in __getTypeTarget
> FileNotFoundError: [Errno 2] No such file or directory: 'level2\\product_a.img'
> [10492] Failed to execute script imgextractor
> Unpack system_a.img
> imgextractor: Vortex Edition
> Traceback (most recent call last):
>   File "imgextractor.py", line 374, in <module>
>   File "imgextractor.py", line 360, in main
>   File "imgextractor.py", line 345, in __getTypeTarget
> FileNotFoundError: [Errno 2] No such file or directory: 'level2\\system_a.img'
> [1620] Failed to execute script imgextractor
> Unpack vendor_a.img
> imgextractor: Vortex Edition
> Traceback (most recent call last):
>   File "imgextractor.py", line 374, in <module>
>   File "imgextractor.py", line 360, in main
>   File "imgextractor.py", line 345, in __getTypeTarget
> FileNotFoundError: [Errno 2] No such file or directory: 'level2\\vendor_a.img'
> [10088] Failed to execute script imgextractor
> Deleting...
> Copy files...
> 0 File(s) copied
> 77 File(s) copied
> Does E:\ATVify_0.0.3\\level2\product\preinstall specify a file name
> or directory name on the target
> (F = file, D = directory)? d
> 13 File(s) copied
> Editing...
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\build.prop: No such file or directory
> bin\sed: can't read level2\product\build.prop: No such file or directory
> bin\sed: can't read level2\vendor\etc\init\hw\init.amlogic.rc: No such file or directory
> bin\sed: can't find label for jump to `in/factoryreset.sh.*$/d'
> bin\sed: can't read level2\vendor_fs_config: No such file or directory
> Build odm_a.img
> 'bin\foldersize' is not recognized as an internal or external command,
> operable program or batch file.
> make_ext4fs Vortex edition
> level2\odm_file_contexts: No such file or directory
> exit was unexpected at this time.
> Traceback (most recent call last):
>   File "atvify.py", line 125, in <module>
> NameError: name 'exit' is not defined. Did you mean: 'atexit'?
> [14196] Failed to execute script 'atvify' due to unhandled exception!

**Comment by t1m0xa** [comment]
> On i have moved the folder to the root of the drive. see the logs below.
> 
> It fails when trying to unpack super.img.raw
> 
> <EDIT> did some reasearch and this could be possible fix, could you confimr?
> https://forum.xda-developers.com/t/extracing-super-img-super2-img-issue-and-mounting-vendor-img.4279879/
> 
> > Firmware unpacking...
> > [Msg]Image package version 0x2
> > [Msg]Unpack item [USB         ,              DDR] to (level1\DDR.USB) size:49152 bytes
> > [Msg]Unpack item [USB         ,            UBOOT] to (level1\UBOOT.USB) size:786432 bytes
> > [Msg]Unpack item [PARTITION   ,         _aml_dtb] to (level1\_aml_dtb.PARTITION) size:59203 bytes
> > [Msg]Unpack item [UBOOT       ,     aml_sdc_burn] to (level1\aml_sdc_burn.UBOOT) size:836096 bytes
> > [Msg]Unpack item [ini         ,     aml_sdc_burn] to (level1\aml_sdc_burn.ini) size:394 bytes
> > [Msg]Unpack item [PARTITION   ,             boot] to (level1\boot.PARTITION) size:9885696 bytes
> > [Msg]Unpack item [PARTITION   ,       bootloader] to (level1\bootloader.PARTITION) size:868352 bytes
> > [Msg]Unpack item [PARTITION   ,             dtbo] to (level1\dtbo.PARTITION) size:438 bytes
> > [Msg]Unpack item [PARTITION   ,             logo] to (level1\logo.PARTITION) size:5048640 bytes
> > [Msg]Backup item [dtb         ,           meson1] backItemId[2][PARTITION, _aml_dtb]
> > [Msg]Unpack item [PARTITION   ,              odm] to (level1\odm.PARTITION) size:540748 bytes
> > [Msg]Unpack item [conf        ,         platform] to (level1\platform.conf) size:202 bytes
> > [Msg]Unpack item [PARTITION   ,          product] to (level1\product.PARTITION) size:3469388 bytes
> > [Msg]Unpack item [PARTITION   ,         recovery] to (level1\recovery.PARTITION) size:16756736 bytes
> > [Msg]Unpack item [PARTITION   ,           system] to (level1\system.PARTITION) size:1344848260 bytes
> > [Msg]Unpack item [PARTITION   ,           vbmeta] to (level1\vbmeta.PARTITION) size:4096 bytes
> > [Msg]Unpack item [PARTITION   ,           vendor] to (level1\vendor.PARTITION) size:106212184 bytes
> > [Msg]Write config file "level1\image.cfg" OK!
> > Image unpack OK!
> > Convert super.img to super.img.raw
> > Cannot open input file level1\super.PARTITION
> > Unpack super.img.raw
> > lpunpack E 07-30 14:06:42   665 15216 reader.cpp:125] [liblp]bool android::fs_mgr::ReadPrimaryGeometry(int, LpMetadataGeometry *) read 4096 bytes failed: No error
> > lpunpack E 07-30 14:06:42   665 15216 reader.cpp:138] [liblp]bool android::fs_mgr::ReadBackupGeometry(int, LpMetadataGeometry *) backup read 4096 bytes failed: No error
> > Image does not appear to be in super-partition format.
> > Unpack odm_a.img
> > imgextractor: Vortex Edition
> > Traceback (most recent call last):
> >   File "imgextractor.py", line 374, in <module>
> >   File "imgextractor.py", line 360, in main
> >   File "imgextractor.py", line 345, in __getTypeTarget
> > FileNotFoundError: [Errno 2] No such file or directory: 'level2\\odm_a.img'
> > [52] Failed to execute script imgextractor
> > Unpack product_a.img
> > imgextractor: Vortex Edition
> > Traceback (most recent call last):
> >   File "imgextractor.py", line 374, in <module>
> >   File "imgextractor.py", line 360, in main
> >   File "imgextractor.py", line 345, in __getTypeTarget
> > FileNotFoundError: [Errno 2] No such file or directory: 'level2\\product_a.img'
> > [10492] Failed to execute script imgextractor
> > Unpack system_a.img
> > imgextractor: Vortex Edition
> > Traceback (most recent call last):
> >   File "imgextractor.py", line 374, in <module>
> >   File "imgextractor.py", line 360, in main
> >   File "imgextractor.py", line 345, in __getTypeTarget
> > FileNotFoundError: [Errno 2] No such file or directory: 'level2\\system_a.img'
> > [1620] Failed to execute script imgextractor
> > Unpack vendor_a.img
> > imgextractor: Vortex Edition
> > Traceback (most recent call last):
> >   File "imgextractor.py", line 374, in <module>
> >   File "imgextractor.py", line 360, in main
> >   File "imgextractor.py", line 345, in __getTypeTarget
> > FileNotFoundError: [Errno 2] No such file or directory: 'level2\\vendor_a.img'
> > [10088] Failed to execute script imgextractor
> > Deleting...
> > Copy files...
> > 0 File(s) copied
> > 77 File(s) copied
> > Does E:\ATVify_0.0.3\\level2\product\preinstall specify a file name
> > or directory name on the target
> > (F = file, D = directory)? d
> > 13 File(s) copied
> > Editing...
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\build.prop: No such file or directory
> > bin\sed: can't read level2\product\build.prop: No such file or directory
> > bin\sed: can't read level2\vendor\etc\init\hw\init.amlogic.rc: No such file or directory
> > bin\sed: can't find label for jump to `in/factoryreset.sh.*$/d'
> > bin\sed: can't read level2\vendor_fs_config: No such file or directory
> > Build odm_a.img
> > 'bin\foldersize' is not recognized as an internal or external command,
> > operable program or batch file.
> > make_ext4fs Vortex edition
> > level2\odm_file_contexts: No such file or directory
> > exit was unexpected at this time.
> > Traceback (most recent call last):
> >   File "atvify.py", line 125, in <module>
> > NameError: name 'exit' is not defined. Did you mean: 'atexit'?
> > [14196] Failed to execute script 'atvify' due to unhandled exception!

I think it because your ROM isn't A/B. So, I will fix it on next update.

**Comment by eagledipesh** [comment]
Great, thankyou will await further updates from you.

**Comment by eagledipesh** [comment]
Just follow up on the issue.
